server:
  port: 8083
  servlet:
    context-path: /api


spring:
  data:
    mongodb:
      uri: mongodb+srv://anjaniy:SalekarAnjaniy@cluster0.nawzwbt.mongodb.net/?retryWrites=true&w=majority
      database: natours-db

